### ISSUE TITLE
Hello, help pls

### ISSUE THREAD

**Issue by AT4S** [yanpaing007/Tomarket#14]
![image](https://github.com/user-attachments/assets/24bbbba2-aad5-4a4c-a62f-54b97856b1e4)

any other scripts work fine, but this one does not work as it should and the problem is not on the Internet, with internet all ok

**Comment by yanpaing007** [comment]
Although It is not a critical error,it will skip current loop and goes immediately to another,I will take a look

**Comment by AT4S** [comment]
updated the repository, does not move on to the next cycle, just floods it

![image](https://github.com/user-attachments/assets/4d25d449-2add-49ba-8f9b-f6d4184f3ff5)

**Comment by yanpaing007** [comment]
Please update the bot and tell me if the issue still occuring
