### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by xMacoy01** [yanpaing007/Tomarket#15]
What is the default of this?

PLAY_RANDOM_GAME_COUNT=
NIGHT_SLEEP=
NIGHT_SLEEP_TIME=

thanks for the update by the way.

**Comment by yanpaing007** [comment]
Default value are already in config.py
If you want to use default safe value,you don't need to add or change anything

PLAY_RANDOM_GAME_COUNT=[380,420]
NIGHT_SLEEP=True
NIGHT_SLEEP_TIME=[[22,23],[3,4]]
