### ISSUE TITLE
Game play ticket not completing,, just collect some tickets, maximum ticket remains

### ISSUE THREAD

**Issue by likhonxyz** [yanpaing007/Tomarket#17]

**Comment by yanpaing007** [comment]
provide your terminal logs

**Comment by likhonxyz** [comment]
![Screenshot_2024-11-19-21-16-49-584_com termux](https://github.com/user-attachments/assets/42aa5f67-2e68-458e-9105-642cb11827b0)
Using script since a week Still a huge collection of Tickets remains.

**Comment by yanpaing007** [comment]
Hey update the bot and give me feedback

**Comment by likhonxyz** [comment]
![Screenshot_2024-11-20-12-42-53-307_com termux](https://github.com/user-attachments/assets/da258c97-4860-4ca0-be7d-03c74c2a7812)
Sorry bro still facing the same problem...tickets are still remain

**Comment by yanpaing007** [comment]
ticket remaining mean now it is playing games,and wait 30 seconds to finish game and see if you got reward for that tg account,

**Comment by yanpaing007** [comment]
From your first pic ,I can see that you got reward from your game play,if you want to use more ticket for game play each round,increase ticket amount in config.py or .env ,I am closing this issue

**Comment by likhonxyz** [comment]
Thnx bro problem solved ♥️
