### ISSUE TITLE
always like this any solution?

### ISSUE THREAD

**Issue by xMacoy01** [yanpaing007/Tomarket#2]
![image](https://github.com/user-attachments/assets/9fcfc7e2-cce3-4836-87dd-cc21821f0ed0)

**Comment by yanpaing007** [comment]
The problem comes from slow internet or unstable internet

**Comment by AT4S** [comment]
i have the same problem, with internet is all ok

**Comment by AT4S** [comment]
![image](https://github.com/user-attachments/assets/2a2c2760-4885-41b5-b031-18f6f46ee7d2)


all scripts work fine, only this one does not work as it should and the problem is not on the Internet

PLEASE FIX IT =(
