### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by WhiteCjy** [yanpaing007/Tomarket#20]
![image](https://github.com/user-attachments/assets/a81f1487-755d-4ca7-a5e1-356f35a04a5a)

what should we do

**Comment by WhiteCjy** [comment]
![image](https://github.com/user-attachments/assets/469c4242-9f2f-4291-914d-d105fc777bfc)

**Comment by xMacoy01** [comment]
delete your session and create new

**Comment by yanpaing007** [comment]
Do you still have this problem?
